version: '3'

services:
  librofirma-db:
    ports:
      - 5433:5432
  librofirma-db-admin:
    image: dpage/pgadmin4
    ports:
      - 18000:80
    links:
      - librofirma-db:db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
  librofirma-be:
    ports:
      - "8080:8080"
    environment:
      DOMAIN: http://78194a74.ngrok.io
      librofirma.frontend.address: http://127.0.0.1
      debug: 'true'
      trace: 'false'
      spring.datasource.url: jdbc:postgresql://db:5432/librofirma-db
      spring.jpa.show-sql: 'true'
      spring.jpa.hibernate.ddl-auto: update
      logging.level.org.hibernate.tool.hbm2ddl: DEBUG
      logging.level.org.hibernate.SQL: DEBUG
      logging.level.org.hibernate.type: TRACE
      # Va in conflitto con linea successiva: impostare quella custom di Hibernate
      #spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
      spring.jpa.properties.javax.persistence.schema-generation.create-source: metadata
      spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: /data/db-schema.sql
  librofirma-fe:
    environment:
      DOMAIN: demo.signingtoday.com
    extra_hosts:
      - backend:172.25.5.10
    #links:
    #  - librofirma-be:backend
