version: '3'

services:
  app:
    build: LibroFirmaDB/
    restart: always
    expose:
      - 5432
    ports:
      - 127.0.0.1:5432:5432
    environment:
      MY_VAR: variable
    volumes:
      #-   ./data/:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


  