version: "3.8"

services:
  app:
    restart: unless-stopped
    ports:
      - "${PORT}:8083"
    networks:
      - back-tier-test
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_PLATFORM: postgres
      JAVA_TOOL_OPTIONS: -Xmx16G -Xms16G
      OPENJ9_JAVA_OPTIONS: -Xverbosegclog:~/verbosegc-openj9.txt
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: unless-stopped
    networks:
      - back-tier-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: bitnami/prometheus
    networks:
      - back-tier-test
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /opt/bitnami/prometheus/conf/prometheus.yml

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - back-tier-test

networks:
  back-tier-test: {}
