version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8085:8083"
    networks:
      - back-tier
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATA_SOURCE_PASSWORD: postgres
      INIT_DATABASE: false
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: unless-stopped
    networks:
      - back-tier
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  back-tier: {}

volumes:
  postgres_data:
    driver: local