version: "3.8"

services:
  app:
    ports:
      - "${PORT}:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;MODE=PostgreSQL;NON_KEYWORDS=YEAR,MONTH
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_PLATFORM: h2
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.H2Dialect
